# Generated by Django 3.2.5 on 2021-08-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=50)),
                ('configuration', models.URLField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('paid_by', models.CharField(max_length=50)),
                ('used_by', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=250)),
                ('item_number', models.PositiveSmallIntegerField()),
                ('empl_start_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
